### ISSUE TITLE
Bower, Component.js... Les packages managers pour le front-end, ça existe !

### ISSUE THREAD

**Issue by MoOx** [aperoweb-toulouse/talks#17]
TODO

**Comment by MoOx** [comment]
outdated

**Comment by DirtyF** [comment]
@MoOx /s/Bower/npm ?

**Comment by MoOx** [comment]
Un peu la flemme j'avoue. Cela dit voilà des pistes:

- http://putaindecode.fr/posts/frontend/npm-comme-package-manager-pour-le-front-end/
- http://putaindecode.fr/posts/js/etat-lieux-js-modulaire-front/

**Comment by hadrienl** [comment]
Je peux vous parler de jspm…

**Comment by DirtyF** [comment]
@hadrienl @MoOx pour un prochain ToulouseJS ?

**Comment by hadrienl** [comment]
C'est quand le prochain toulousejs ?

**Comment by DirtyF** [comment]
fin août il me semble, faut demander à @maxdow

**Comment by hadrienl** [comment]
J'y vais ;)
